"""The reversal study's declaration, its refusal to reuse consumed days, and its arithmetic.

WHY THIS FILE EXISTS. This study was built on a hypothesis generated by an *already measured*
window, which is the one situation where a programme like this can quietly fool itself: flip
the sign, re-test the same days, report a fresh-looking t-statistic. The guard is structural, so
it is pinned structurally — the primary sample must be disjoint from the days the momentum study
consumed, and that is asserted against the artifacts rather than trusted to the harness.

The second pin is the verdict: it must be the declared three-way rule applied to the numbers
recorded in the artifact, so neither the verdict nor the numbers can drift apart.
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import gold_reversal_into_close as rev  # noqa: E402

PROTOCOL = ROOT / "docs" / "GOLD_REVERSAL_INTO_CLOSE_PROTOCOL.md"
VERDICT = ROOT / "docs" / "GOLD_REVERSAL_INTO_CLOSE_VERDICT_20260921.md"
ART = ROOT / "artifacts" / "gold_reversal_into_close.json"
MOMENTUM_ART = ROOT / "artifacts" / "gold_intraday_momentum.json"
M15 = ROOT / "data" / "forex" / "xauusd" / "XAUUSD_M15_upcomers.csv"


def _load(p: Path) -> dict:
    if not p.is_file():
        pytest.skip(f"{p.name} not generated in this checkout")
    return json.loads(p.read_text(encoding="utf-8"))


# --- the harness's own arithmetic ---------------------------------------------------------

def test_selftest_passes(capsys) -> None:
    assert rev.selftest() == 0
    assert "13/13 passed" in capsys.readouterr().out


# --- the declaration ----------------------------------------------------------------------

def test_the_protocol_declares_the_reversal_sign() -> None:
    text = PROTOCOL.read_text(encoding="utf-8")
    assert "b < 0" in text
    assert "rejects" in text and "H2" in text


def test_the_protocol_refuses_the_consumed_window_as_evidence() -> None:
    text = PROTOCOL.read_text(encoding="utf-8")
    assert "consumed" in text.lower()
    assert "second look" in text.lower()


def test_the_protocol_declares_the_required_sample_before_the_run() -> None:
    text = PROTOCOL.read_text(encoding="utf-8")
    assert "0.0046R/day" in text
    assert "≈ 4,800" in text, "the pre-declared required sample must be on the page"


def test_the_declared_constants_are_what_the_code_uses() -> None:
    assert rev.STANDARD_FINAL_STAMP == "22:30"
    assert rev.MIN_BARS == 40
    assert rev.FORWARD_FROM == "2026-09-21"


# --- the structural guard: consumed days are never re-tested ------------------------------

def test_the_primary_sample_is_disjoint_from_the_consumed_days() -> None:
    """The whole point. If this ever fails, the study has become a second look at the same
    outcomes with the sign flipped, and its p-value means nothing."""
    art, mom = _load(ART), _load(MOMENTUM_ART)
    consumed = {r["day"] for r in mom["rows"]}
    primary = {r["day"] for r in art["rows_primary"]}
    auxiliary = {r["day"] for r in art["rows_auxiliary"]}
    assert primary and auxiliary
    assert not (primary & consumed), "primary sample re-tests consumed days"
    assert not (auxiliary & consumed), "auxiliary sample re-tests consumed days"
    assert not (primary & auxiliary)


def test_the_recorded_sample_counts_match_the_declared_selector() -> None:
    if not M15.is_file():
        pytest.skip("venue M15 series not present")
    import midas_sweep as ms
    import gold_intraday_momentum as gim
    art = _load(ART)
    days = gim.by_day(ms.load_bars(str(M15)))
    consumed = rev.consumed_days(str(MOMENTUM_ART))
    primary_days, aux_days = rev.samples(days, consumed)
    assert art["primary_sample_days"] == len(art["rows_primary"]) <= len(primary_days)
    assert art["consumed_days"] + art["unconsumed_days"] == len(days)
    # the selector's output is the declared rule's; rows can only be fewer (ATR/era refusals)
    assert set(r["day"] for r in art["rows_primary"]) <= set(primary_days)
    assert set(r["day"] for r in art["rows_auxiliary"]) <= set(aux_days)


def test_the_primary_rows_only_contain_the_declared_shape() -> None:
    art = _load(ART)
    for r in art["rows_primary"]:
        assert r["anchor"] == "00:00"
        assert r["final_pair"].split("->")[-1] < rev.STANDARD_FINAL_STAMP


def test_the_consumed_list_comes_from_the_momentum_artifact() -> None:
    mom = _load(MOMENTUM_ART)
    assert len(rev.consumed_days(str(MOMENTUM_ART))) == len(mom["rows"])


def test_missing_consumed_list_is_fatal_not_guessed(tmp_path: Path) -> None:
    with pytest.raises(SystemExit) as e:
        rev.consumed_days(str(tmp_path / "absent.json"))
    assert "consumed-day list" in str(e.value)


# --- the artifact agrees with its own rule -----------------------------------------------

def test_the_recorded_primary_numbers_recompute_from_the_rows() -> None:
    art = _load(ART)
    rows = art["rows_primary"]
    n = len(rows)
    p = art["primary"]
    assert n == p["n"]
    mean = sum(r["net_r"] for r in rows) / n
    sd = math.sqrt(sum((r["net_r"] - mean) ** 2 for r in rows) / (n - 1))
    assert abs(mean - p["mean"]) < 5e-4
    assert abs(sd - p["sd"]) < 5e-4
    assert abs(p["mde"] - (1.96 + 0.8416) * sd / math.sqrt(n)) < 5e-4


def test_the_recorded_verdict_is_the_declared_rule_applied_to_the_recorded_numbers() -> None:
    import gold_intraday_momentum as gim
    art = _load(ART)
    for block in ("primary", "auxiliary_descriptive"):
        s = art[block]
        assert gim.verdict(s, [e for e in s["per_era"] if e["n"] >= 2])[0] == s["verdict"]


def test_the_auxiliary_is_labelled_descriptive_in_both_places() -> None:
    art = _load(ART)
    assert "DESCRIPTIVE ONLY" in art["auxiliary_descriptive"]["note"]
    assert "descriptive" in PROTOCOL.read_text(encoding="utf-8").lower()


def test_the_reversal_direction_is_actually_reversed_in_the_rows() -> None:
    """A day that closed up must be traded SHORT and its gross must be the negative of the
    final move — the invariant that makes this a reversal study and not another momentum run."""
    art = _load(ART)
    for r in art["rows_primary"]:
        if r["r_rod"] > 0:
            assert r["side"] == "short"
        elif r["r_rod"] < 0:
            assert r["side"] == "long"
        # the R columns are the dollars divided by the declared stop, and the direction-signed
        # return agrees in sign with the direction-signed price move
        assert r["gross_r"] == pytest.approx(r["gross_usd"] / r["stop_usd"], abs=1e-9)
        assert r["cost_r"] == pytest.approx(r["cost_usd"] / r["stop_usd"], abs=1e-9)
        assert r["net_r"] == pytest.approx((r["gross_usd"] - r["cost_usd"]) / r["stop_usd"],
                                           abs=1e-9)
        assert (r["r_lh"] >= 0) == (r["gross_r"] >= 0)


def test_the_counterfactual_direction_is_disclosed_as_descriptive() -> None:
    text = VERDICT.read_text(encoding="utf-8")
    assert "mirror (momentum) direction" in text.lower()
    assert "descriptive only" in text.lower()


def test_the_verdict_document_names_the_one_day_it_depends_on() -> None:
    """The pooled mean's sign flips without 2026-01-27; a verdict that hides that is not a
    verdict, it is a summary."""
    text = VERDICT.read_text(encoding="utf-8")
    assert "2026-01-27" in text and "0.0045R" in text.replace("+", "")


def test_the_data_of_record_is_the_venue_series() -> None:
    art = _load(ART)
    joined = " ".join(art["data_of_record"])
    assert "upcomers" in joined and "frozen_corpus" not in joined


def test_the_verdict_document_exists_when_the_artifact_does() -> None:
    _load(ART)
    assert VERDICT.is_file()
