"""Reversal into the venue's close, on the slice the momentum study did not consume.

This implements `docs/GOLD_REVERSAL_INTO_CLOSE_PROTOCOL.md` and nothing else. The hypothesis
was generated by the consumed window (the momentum study's +120 era read net −0.0210R/day,
t −2.00), so the consumed days are REFUSED as evidence here: a reversal test on them would be a
second look at the same outcomes with the sign flipped.

WHAT IT TESTS ON INSTEAD. The only gold days the momentum study did not produce an observation
for are the 32 it skipped for completeness — 22 with the venue's own 00:00 anchor whose close
moved earlier (US early-close days), and 10 whose day-anchor bar is missing. The primary sample
is the first group; the second is reported as a pre-declared descriptive auxiliary, because its
anchor moves between 00:00, 01:00, 01:15 and 13:15 and those days are not one population.

The consumed list is read from `artifacts/gold_intraday_momentum.json`. Without it the script
refuses rather than guessing what has been seen — "which days are consumed" is the one input
that cannot be reconstructed from the bars.

Run:  python scripts/gold_reversal_into_close.py
      python scripts/gold_reversal_into_close.py --selftest
      python scripts/gold_reversal_into_close.py --forward     # include days after 2026-09-21
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gold_intraday_momentum as gim   # noqa: E402  — the shared, tested helpers
import midas_sweep as ms               # noqa: E402

MOMENTUM_ART = os.path.join("artifacts", "gold_intraday_momentum.json")
ARTIFACT = os.path.join("artifacts", "gold_reversal_into_close.json")
M15_PATH = gim.M15_PATH
H1_PATH = gim.H1_PATH

#: Declared in the protocol. The standard close pair's second stamp is 22:30; a day whose final
#: stamp is earlier closed early, and those are exactly the days the momentum study skipped.
STANDARD_FINAL_STAMP = "22:30"
MIN_BARS = 40                            # enough of a day to have a "day so far"
FORWARD_FROM = "2026-09-21"              # the venue's close on this day onward is un-consumed


def consumed_days(path: str = MOMENTUM_ART) -> set[str]:
    """The days the momentum study produced an observation for. Refuses if unavailable."""
    try:
        with open(path) as fh:
            rows = json.load(fh)["rows"]
    except (OSError, KeyError, json.JSONDecodeError) as exc:
        raise SystemExit(
            f"cannot read the consumed-day list {path}: {exc}\n"
            f"      -> without it this script cannot tell which days have already been looked\n"
            f"         at, and a reversal test on consumed days is a second look, not a test.\n"
            f"         Re-run scripts/gold_intraday_momentum.py first.")
    return {r["day"] for r in rows}


def day_row(day: str, bars: dict[str, dict], atr_lookup, anchor: str) -> dict | None:
    """One observation, with the direction AGAINST the day's move, or None with a reason."""
    stamps = sorted(bars)
    if anchor not in bars or len(stamps) < 2:
        return None
    l_minus, last = bars[stamps[-2]], bars[stamps[-1]]
    a = bars[anchor]
    r_rod = l_minus["open"] / a["open"] - 1.0
    if r_rod == 0.0:
        return None
    stop = gim.atr_at(atr_lookup, l_minus["time"])
    if not stop or stop <= 0:
        return None
    stop *= gim.STOP_ATR_MULT
    direction = -1.0 if r_rod > 0 else 1.0            # the declared reversal
    gross = direction * (last["close"] - l_minus["open"])
    cost = (max(l_minus["spread"], ms.SPREAD_FLOOR) / 2.0
            + max(last["spread"], ms.SPREAD_FLOOR) / 2.0)
    off = gim.era_offset(day)
    return {
        "day": day, "r_rod": r_rod,
        "r_lh": direction * (last["close"] / l_minus["open"] - 1.0),
        "side": "long" if direction > 0 else "short",
        "anchor": anchor, "final_pair": f"{stamps[-2]}->{stamps[-1]}",
        "gross_usd": gross, "cost_usd": cost, "net_usd": gross - cost, "stop_usd": stop,
        "gross_r": gross / stop, "cost_r": cost / stop, "net_r": (gross - cost) / stop,
        "entry_ct": l_minus["time"], "era_offset_min": off,
        "entry_utc": gim._utc(l_minus["time"] - (off or 0) * 60).strftime("%Y-%m-%d %H:%M"),
    }


def samples(days: dict[str, dict], consumed: set[str]) -> tuple[list[str], list[str]]:
    """(primary days, auxiliary days) exactly as the protocol defines them."""
    primary, auxiliary, seen = [], [], set()
    for day in sorted(days):
        if day in consumed or day in seen:
            continue
        bars = days[day]
        stamps = sorted(bars)
        if len(stamps) < MIN_BARS:
            continue
        if "00:00" in bars and stamps[-1] < STANDARD_FINAL_STAMP:
            primary.append(day)
        else:
            auxiliary.append(day)
    return primary, auxiliary


def collect(day_list: list[str], days: dict[str, dict], atr_lookup, *,
            anchor_policy: str) -> list[dict]:
    rows = []
    for day in day_list:
        bars = days[day]
        anchor = "00:00" if (anchor_policy == "day_open" and "00:00" in bars) else sorted(bars)[0]
        row = day_row(day, bars, atr_lookup, anchor)
        if row is not None and row["era_offset_min"] is not None:
            rows.append(row)
    return rows


def era_blocks(rows: list[dict]) -> list[dict]:
    out = []
    for off in sorted({r["era_offset_min"] for r in rows}):
        sub = [r for r in rows if r["era_offset_min"] == off]
        if len(sub) < 2:
            continue
        out.append({"era_offset_min": off,
                    "utc_lh_window": f"{sub[0]['entry_utc'][-5:]} UTC + 30m",
                    **gim.stats(sub, "net_r")})
    return out


def summarise(rows: list[dict]) -> dict:
    if len(rows) < 2:
        return {"n": len(rows), "mean": None, "t": None, "mde": None, "note":
                "too few observations to compute a statistic"}
    pooled = gim.stats(rows, "net_r")
    eras = era_blocks(rows)
    v, why = gim.verdict(pooled, eras)
    return {**pooled, "win_rate": round(sum(1 for r in rows if r["net_r"] > 0) / pooled["n"], 3),
            "gross": gim.stats(rows, "gross_r"), "cost": gim.stats(rows, "cost_r"),
            "per_era": eras, "regression_r_lh_on_r_rod_pct": gim.slope(rows),
            "verdict": v, "why": why}


def run(forward: bool = False) -> dict:
    consumed = consumed_days()
    days = gim.by_day(ms.load_bars(M15_PATH))
    atr_lookup = gim.h1_atr_lookup(ms.load_bars(H1_PATH))
    primary_days, aux_days = samples(days, consumed)
    if forward:                                  # the declared forward primary, when it exists
        # Forward days enter the primary sample through the SAME declared shape filter as
        # every other day — `samples()` has already applied it, and the unconditional append
        # this used to do was a second, looser selector: measured 2026-09-23, it admitted
        # 2026-09-22 (final stamp 22:45, past the declared 22:30 boundary) into the primary
        # rows, so the artifact contradicted its own selector on the same run (pinned by
        # tests/test_gold_reversal_into_close.py). The forward declaration (protocol
        # §Declared forward primary) is a DATE extension of the declared rule, not a
        # different rule: shaped forward days (2026-09-23) join the primary here because
        # they already sit in `primary_days`, unshaped ones stay out of it.
        aux_days = [d for d in aux_days if d <= FORWARD_FROM]

    primary = collect(primary_days, days, atr_lookup, anchor_policy="day_open")
    auxiliary = collect(aux_days, days, atr_lookup, anchor_policy="first_available")
    res = {
        "what": "reversal into the venue's close, on the momentum study's unconsumed slice",
        "protocol": "docs/GOLD_REVERSAL_INTO_CLOSE_PROTOCOL.md",
        "hypothesis": "r_LH' predicted by r_ROD' with the OPPOSITE sign (trade against the day)",
        "data_of_record": [M15_PATH, H1_PATH],
        "consumed_days": len(consumed),
        "unconsumed_days": len(days) - len(consumed),
        "primary_sample_days": len(primary),
        "sample_rule": {"anchor": "00:00", "final_stamp_before": STANDARD_FINAL_STAMP,
                        "min_bars": MIN_BARS, "not_consumed": True},
        "primary": summarise(primary),
        "auxiliary_descriptive": {**summarise(auxiliary),
                                  "note": "DESCRIPTIVE ONLY (pre-declared): the anchor moves "
                                          "between 00:00/01:00/01:15/13:15 across these days"},
        "rows_primary": primary,
        "rows_auxiliary": auxiliary,
        "forward_from": FORWARD_FROM if forward else None,
    }
    with open(ARTIFACT, "w") as fh:
        json.dump(res, fh, indent=1)
    return res


def _report(tag: str, s: dict) -> None:
    if s.get("mean") is None:
        print(f"  {tag}: {s['n']} observation(s) — {s.get('note', 'insufficient')}")
        return
    print(f"  {tag}: n={s['n']}  gross {s['gross']['mean']:+.4f}R  cost {s['cost']['mean']:.4f}R"
          f"  NET {s['mean']:+.4f}R/day  t {s['t']:+.2f}  win {s['win_rate']:.1%}"
          f"  MDE {s['mde']:.4f}")
    for e in s["per_era"]:
        print(f"      era +{e['era_offset_min']:>3} min ({e['utc_lh_window']}): "
              f"{e['mean']:+.4f}R  t {e['t']:+.2f}  n {e['n']}")
    print(f"      regression b {s['regression_r_lh_on_r_rod_pct']['b']} "
          f"(t {s['regression_r_lh_on_r_rod_pct']['t']}) — H2 wants b < 0")
    print(f"      VERDICT: {s['verdict']} — {s['why']}")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--forward", action="store_true",
                    help=f"include un-consumed days after {FORWARD_FROM}")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--json-only", action="store_true")
    args = ap.parse_args(argv)
    if args.selftest:
        return selftest()
    res = run(args.forward)
    if args.json_only:
        print(json.dumps({k: v for k, v in res.items() if not k.startswith("rows_")}, indent=1))
        return 0
    print(f"\nreversal into the venue's close | consumed {res['consumed_days']} of "
          f"{res['consumed_days'] + res['unconsumed_days']} stamped days | primary sample "
          f"{res['primary_sample_days']}")
    _report("PRIMARY   ", res["primary"])
    _report("AUXILIARY ", res["auxiliary_descriptive"])
    print(f"\nartifact: {ARTIFACT}")
    return 0


def selftest() -> int:
    """The harness's own invariants, on cases whose answer is known by construction."""
    checks = []
    atr = [(ms.iso_to_ts("2026-05-04 00:00"), 5.0)]

    def bar(hhmm, o, c, spread=0.30, day="2026-05-04"):
        t = ms.iso_to_ts(f"{day} {hhmm}")
        return {"time": t, "open": o, "high": max(o, c), "low": min(o, c), "close": c,
                "spread": spread}

    up = {"00:00": bar("00:00", 100.0, 100.0), "21:30": bar("21:30", 101.0, 101.0),
          "21:45": bar("21:45", 101.0, 101.45)}
    r = day_row("2026-05-04", up, atr, "00:00")
    checks.append(("the day was up, so the trade is SHORT", r["side"] == "short"))
    checks.append(("gross is the reversal of the final move",
                   abs(r["gross_usd"] - (101.0 - 101.45)) < 1e-9))
    down = {"00:00": bar("00:00", 100.0, 100.0), "21:30": bar("21:30", 99.0, 99.0),
            "21:45": bar("21:45", 99.0, 98.55)}
    checks.append(("a down day trades LONG",
                   day_row("2026-05-04", down, atr, "00:00")["side"] == "long"))
    checks.append(("cost is one round-trip spread, floored",
                   abs(r["cost_usd"] - 0.30) < 1e-9
                   and abs(day_row("2026-05-04",
                                   {**up, "21:30": {**up["21:30"], "spread": 0.0},
                                    "21:45": {**up["21:45"], "spread": 0.0}}, atr,
                                   "00:00")["cost_usd"] - 0.10) < 1e-9))
    checks.append(("a flat day is skipped",
                   day_row("2026-05-04", {**up, "21:30": {**up["21:30"], "open": 100.0},
                                          "21:45": {**up["21:45"], "open": 100.0}},
                           atr, "00:00") is None))
    checks.append(("a missing anchor is skipped", day_row("2026-05-04", up, atr, "00:00") is not None
                   and day_row("2026-05-04", {k: v for k, v in up.items() if k != "00:00"},
                               atr, "00:00") is None))
    # selection: consumed days are refused, and an early close puts a day in the primary
    # sample. The fixtures are full days (>= MIN_BARS stamps), because a short day is meant to
    # be excluded and a four-bar fixture would test nothing but that exclusion.
    def span(first: str, last: str) -> dict:
        out, h, m = {}, int(first[:2]), int(first[3:])
        end = int(last[:2]) * 60 + int(last[3:])
        while h * 60 + m <= end:
            out[f"{h:02d}:{m:02d}"] = {}
            m += 15
            if m == 60:
                h, m = h + 1, 0
        return out

    days = {"2026-05-04": span("00:00", "21:45"),      # early close, day anchor
            "2026-05-05": span("00:00", "22:45"),      # standard close
            "2026-05-06": span("01:00", "21:45"),      # no day anchor
            "2026-05-07": span("00:00", "21:45"),      # consumed below
            "2026-05-08": span("00:00", "06:00")}      # too few bars
    prim, aux = samples(days, {"2026-05-07"})
    checks.append(("early close + day anchor -> primary", prim == ["2026-05-04"]))
    checks.append(("standard close -> auxiliary", "2026-05-05" in aux))
    checks.append(("missing day anchor -> auxiliary", "2026-05-06" in aux))
    checks.append(("consumed days are refused", "2026-05-07" not in prim + aux))
    checks.append(("a day with too few bars is ignored",
                   "2026-05-08" not in prim + aux and len(days["2026-05-08"]) < MIN_BARS))
    checks.append(("the consumed list comes from the momentum artifact",
                   len(consumed_days()) > 100))
    # the decision rule is the shared, declared one
    good = [{"net_r": 0.2 + 0.01 * i} for i in range(20)]
    checks.append(("a positive mean with both eras positive PASSes",
                   gim.verdict(gim.stats(good, "net_r"),
                               [{"n": 10, "mean": 0.2}, {"n": 10, "mean": 0.25}])[0] == "PASS"))
    bad = [name for name, ok in checks if not ok]
    for name, ok in checks:
        print(f"  {'ok  ' if ok else 'FAIL'}  {name}")
    print(f"\nselftest: {len(checks) - len(bad)}/{len(checks)} passed")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
